id: AIRFLOW_CONFIGURATION_EXPOSURE
info:
  name: Apache Airflow Configuration Exposure
  description: "Attacker can get unauthorized access to Apache Airflow configuration files."
  details: >
    "Apache Airflow Configuration Exposure is a vulnerability that arises from misconfigured settings in Apache Airflow, an open-source workflow management platform. The misconfiguration exposes critical configuration files containing sensitive information, such as API keys and database credentials. This vulnerability could lead to unauthorized access and potential data breaches. Attackers can exploit the exposed configurations to gain unauthorized access, manipulate workflows, and compromise the integrity and confidentiality of the system. It is crucial to address this issue promptly to mitigate the risk of unauthorized access and protect sensitive data."
  impact: "Attackers can exploit exposed configurations to gain unauthorized access and compromise the system's integrity and confidentiality."
  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: AIRFLOW_CONFIGURATION_EXPOSURE
  severity: MEDIUM
  references:
    - https://beaglesecurity.com/blog/vulnerability/apache-airflow-configuration-exposure.html
    - https://www.acunetix.com/vulnerabilities/web/apache-airflow-exposed-configuration/
    - https://thehackernews.com/2021/10/poorly-configured-apache-airflow.html
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-200
    - CWE-213
  cve:
    - CVE-2023-35005

attributes:
  nature: INTRUSIVE
  plan: FREE
  duration: FAST
compliance_standards:
  GDPR:
    - Article 32
    - Article 25
  HIPAA:
    - 45 CFR ยง 164.308(a)(1)(ii)(A)
    - 45 CFR ยง 164.312(a)(2)(i)
  SOC 2:
    - System Configuration and Management Controls
    - Access and Authorization Settings
  PCI DSS:
    - Requirement 2.2
    - Requirement 6.2
  ISO 27001:
    - A.12.1.1
    - A.12.6.2
  NIST 800-53:
    - CM-6
    - AC-17
  CSA CCM:
    - IVS-09
    - TVM-04
  CIS Controls:
    - IG1 Safeguard 4.6
    - IG1 Safeguard 5.5
  FedRAMP:
    - CM-6
    - AC-17
  NIST 800-171:
    - 3.4.6
    - 3.5.7
  FISMA:
    - CM-6
    - AC-17
  Cybersecurity Maturity Model Certification (CMMC):
    - CM.2.068
    - AC.2.008
api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300
  url:
    extract: urlVar

execute:
  type: single
  requests:
    - req:
        - modify_url: ${urlVar}/airflow.cfg

validate:
  response_code:
    gte: 200
    lt: 300
  response_payload:
    contains_all:
      - '[core]'
      - '[api]'
    length:
      gt: 0
    not_contains:
      - <html>
      - </html>
