id: AMAZON_DOCKER_CONFIG
info:
  name: Dockerrun AWS Configuration Exposure
  description: "Attackers can get access to sensitive AWS Dockerrun configuration files."
  details: >
    "Dockerrun AWS Configuration Exposure refers to the vulnerability arising from misconfigured AWS Dockerrun configuration files. This misconfiguration allows unauthorized access to sensitive files, potentially exposing critical information and compromising system security. Attackers can exploit this vulnerability to manipulate container definitions, leading to potential disruptions in system integrity and availability. It is crucial to address this issue promptly to prevent unauthorized access and protect the system from potential risks."
  impact: "Unauthorized access enables manipulation of container definitions, risking system integrity and availability."
  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: AMAZON_DOCKER_CONFIG
  severity: MEDIUM
  references:
    - https://beaglesecurity.com/blog/vulnerability/dockerrun-aws-configuration-exposure.html
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-200
    - CWE-213
  cve:
    - CVE-2020-14329

attributes:
  nature: INTRUSIVE
  plan: FREE
  duration: FAST
compliance_standards:
  GDPR:
    - Article 32
    - Article 25
  HIPAA:
    - 45 CFR ยง 164.308(a)(1)(ii)(A)
    - 45 CFR ยง 164.312(a)(2)(i)
  SOC 2:
    - System Configuration and Management Controls
    - Access and Authorization Settings
  PCI DSS:
    - Requirement 2.2
    - Requirement 6.2
  ISO 27001:
    - A.12.1.1
    - A.12.6.2
  NIST 800-53:
    - CM-6
    - AC-17
  CSA CCM:
    - IVS-09
    - TVM-04
  CIS Controls:
    - IG1 Safeguard 4.6
    - IG1 Safeguard 5.5
  FedRAMP:
    - CM-6
    - AC-17
  NIST 800-171:
    - 3.4.6
    - 3.5.7
  FISMA:
    - CM-6
    - AC-17
  Cybersecurity Maturity Model Certification (CMMC):
    - CM.2.068
    - AC.2.008
api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300
  url:
    extract: urlVar

execute:
  type: single
  requests:
    - req:
        - modify_url: ${urlVar}/Dockerrun.aws.json

validate:
  response_code:
    gte: 200
    lt: 300
  response_payload:
    contains_all:
      - 'AWSEBDockerrunVersion'
      - 'containerDefinitions'
    length:
      gt: 0
    not_contains:
      - <html>
      - </html>
settings:
  duration: FAST
