id: APPSPEC_YML_DISCLOSURE
info:
  name: Appspec Yml Disclosure
  description: "Attackers can get access to the appspec.yml file used in application deployments."
  details: >
    "Appspec Yml Disclosure refers to the vulnerability where the appspec.yml file, crucial for application deployments, is exposed due to misconfiguration. Unauthorized access to this file reveals sensitive deployment information, including version details, operating system specifications, and file information. Attackers can exploit this exposure to gain insights into the deployment process, identify potential vulnerabilities, and execute unauthorized modifications or disruptions to the application. Promptly addressing this issue is essential to prevent unauthorized access and protect the application's integrity and availability."
  impact: "Unauthorized access reveals deployment details, enabling potential exploitation, unauthorized modifications, and disruptions to the application."
  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: APPSPEC_YML_DISCLOSURE
  severity: MEDIUM
  references:
    - https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/appsec-yml-disclosure.json
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-200
    - CWE-213

attributes:
  nature: NON_INTRUSIVE
  plan: FREE
  duration: FAST
compliance_standards:
  GDPR:
    - Article 32
    - Article 25
  HIPAA:
    - 45 CFR ยง 164.308(a)(1)(ii)(A)
    - 45 CFR ยง 164.312(a)(2)(i)
  SOC 2:
    - System Configuration and Management Controls
    - Access and Authorization Settings
  PCI DSS:
    - Requirement 2.2
    - Requirement 6.2
  ISO 27001:
    - A.12.1.1
    - A.12.6.2
  NIST 800-53:
    - CM-6
    - AC-17
  CSA CCM:
    - IVS-09
    - TVM-04
  CIS Controls:
    - IG1 Safeguard 4.6
    - IG1 Safeguard 5.5
  FedRAMP:
    - CM-6
    - AC-17
  NIST 800-171:
    - 3.4.6
    - 3.5.7
  FISMA:
    - CM-6
    - AC-17
  Cybersecurity Maturity Model Certification (CMMC):
    - CM.2.068
    - AC.2.008
api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300
  url:
    extract: urlVar

wordLists:
  urlPaths:
    - ${urlVar}/appspec.yml
    - ${urlVar}/appspec.yaml

execute:
  type: single
  requests:
    - req:
        - modify_url: ${urlPaths}


validate:
  response_code:
    eq: 200
  response_payload:
    length:
      gt: 0
    not_contains:
      - <html>
      - </html>
    contains_all:
      - "version:"
      - "os:"
      - "files:"
