id: CONFIGURATION_LISTING
info:
  name: Sensitive Configuration Files Listing
  description: "Directory listing of sensitive files."
  details: >
    "Sensitive Configuration Files Listing refers to the vulnerability where the misconfiguration allows the listing of sensitive configuration files located in the "config" directory. This exposure can disclose critical information like database credentials and API keys, posing a significant risk to the application's security. Promptly addressing this vulnerability is essential to prevent unauthorized access and protect sensitive data from exploitation."
  impact: "Listing sensitive configuration files exposes critical information, such as database credentials and API keys, enabling targeted attacks and unauthorized access."
  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: CONFIGURATION_LISTING
  severity: MEDIUM
  references:
    - https://www.exploit-db.com/ghdb/7014
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-548
  cve:
    - CVE-2021-1126
    - CVE-2021-33214

attributes:
  nature: NON-INTRUSIVE
  plan: STANDARD
  duration: FAST
compliance_standards:
  GDPR:
    - Article 32
    - Article 25
  HIPAA:
    - 45 CFR ยง 164.308(a)(1)(ii)(A)
    - 45 CFR ยง 164.312(a)(2)(i)
  SOC 2:
    - System Configuration and Management Controls
    - Access and Authorization Settings
  PCI DSS:
    - Requirement 2.2
    - Requirement 6.2
  ISO 27001:
    - A.12.1.1
    - A.12.6.2
  NIST 800-53:
    - CM-6
    - AC-17
  CSA CCM:
    - IVS-09
    - TVM-04
  CIS Controls:
    - IG1 Safeguard 4.6
    - IG1 Safeguard 5.5
  FedRAMP:
    - CM-6
    - AC-17
  NIST 800-171:
    - 3.4.6
    - 3.5.7
  FISMA:
    - CM-6
    - AC-17
  Cybersecurity Maturity Model Certification (CMMC):
    - CM.2.068
    - AC.2.008
api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300
  url:
    extract: urlVar

execute:
  type: single
  requests:
    - req:
        - modify_url: ${urlVar}/config/

validate:
  response_code:
    eq: 200
  response_payload:
    length:
      gt: 0
    not_contains:
      - <html>
      - </html>
    contains_all:
      - "Index of /configs"
      - "Parent Directory"
