id: DOCKER_COMPOSE_CONFIG
info:
  name: docker-compose.yml exposure
  description: "Attacker can get unauthorized access of Docker Compose configuration files."
  details: >
    "Docker Compose.yml Exposure refers to the vulnerability where Docker Compose configuration files, such as docker-compose.yml and related variants, are exposed due to misconfiguration. Unauthorized access to these files can reveal sensitive information about the containerized application, including its services, configurations, and version details. Attackers can exploit this exposure to identify weaknesses, manipulate container settings, and potentially compromise the security of the application's environment. Promptly addressing this vulnerability is essential to prevent unauthorized access, protect sensitive data, and maintain the overall security of the containerized application."
  impact: "Exposing Docker Compose configuration files allows attackers to gain insights into the application's containerized structure, services, and configurations. This information can be exploited to identify weaknesses, manipulate container settings, and potentially compromise the application's security."
  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: DOCKER_COMPOSE_CONFIG
  severity: MEDIUM
  references:
    - https://beaglesecurity.com/blog/vulnerability/docker-compose-yml-exposure.html
    - https://secapps.com/vulndb/docker-compose-exposure
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-16
    - CWE-530
    - CWE-552
    - CWE-538
  cve:
    - CVE-2023-37273

attributes:
  nature: NON-INTRUSIVE
  plan: STANDARD
  duration: FAST
compliance_standards:
  GDPR:
    - Article 32
    - Article 25
  HIPAA:
    - 45 CFR ยง 164.308(a)(1)(ii)(A)
    - 45 CFR ยง 164.312(a)(2)(i)
  SOC 2:
    - System Configuration and Management Controls
    - Access and Authorization Settings
  PCI DSS:
    - Requirement 2.2
    - Requirement 6.2
  ISO 27001:
    - A.12.1.1
    - A.12.6.2
  NIST 800-53:
    - CM-6
    - AC-17
  CSA CCM:
    - IVS-09
    - TVM-04
  CIS Controls:
    - IG1 Safeguard 4.6
    - IG1 Safeguard 5.5
  FedRAMP:
    - CM-6
    - AC-17
  NIST 800-171:
    - 3.4.6
    - 3.5.7
  FISMA:
    - CM-6
    - AC-17
  Cybersecurity Maturity Model Certification (CMMC):
    - CM.2.068
    - AC.2.008
api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300
  url:
    extract: urlVar
  response_payload:
    length:
      gt: 0
    not_contains:
      - Error
      - Internal Server
      - Failed
      - Unauthorized
      - access denied
      - Forbidden
      - Method Not allowed
      - Gateway timeout
      - request timeout
      - server error
      - server busy
      - authentication error
      - authorization error
      - validation error
      - Permission Denied
      - invalid token
      - token expired
      - session expired
      - session timeout
      - unexpected error
      - unable to process request
      - bad request
      - service unavailable
      - account is locked
      - account is blocked
      - multiple failed attempts


wordLists:
  urlPaths:
    - ${urlVar}/docker-compose.yml
    - ${urlVar}/docker-compose.prod.yml
    - ${urlVar}/docker-compose.production.yml
    - ${urlVar}/docker-compose.staging.yml
    - ${urlVar}/docker-compose.dev.yml
    - ${urlVar}/docker-compose-dev.yml
    - ${urlVar}/docker-compose.override.yml

execute:
  type: single
  requests:
    - req:
        - modify_url: ${urlPaths}
        - follow_redirect: true

validate:
  response_code:
    eq: 200
  response_payload:
    contains_all:
      - 'version:'
      - 'services:'
      - "web:"
      - "database:"
      - "environment:"
      - "volumes:"
      - "ports:"
      - "networks:"
    not_contains:
      - Error
      - Internal Server
      - Failed
      - Unauthorized
      - access denied
      - Forbidden
      - Method Not allowed
      - Gateway timeout
      - request timeout
      - server error
      - server busy
      - authentication error
      - authorization error
      - validation error
      - Permission Denied
      - invalid token
      - token expired
      - session expired
      - session timeout
      - unexpected error
      - unable to process request
      - bad request
      - service unavailable
      - account is locked
      - account is blocked
      - multiple failed attempts
      - failure
      - not available
      - not found
      - <html>
      - </html>
