id: GIT_CONFIG
info:
  name: Git Config Disclosure
  description: "Searches for the pattern /.git/config and log file on passed URLs."
  details: >
    "Git Config Disclosure refers to the vulnerability where the existence of the /.git/config file and log files is checked on provided URLs. The Git config file contains sensitive information such as repository configurations, URLs, and credentials, while log files may contain valuable data. Promptly addressing this vulnerability is crucial to prevent unauthorized access, protect source code integrity, and safeguard sensitive information."
  impact: "Disclosing the Git config file and log files exposes sensitive information, allowing attackers to gain unauthorized access, manipulate code, and potentially compromise the integrity of the source code."
  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: GIT_CONFIG
  severity: MEDIUM
  references:
    - https://pentester.land/blog/source-code-disclosure-via-exposed-git-folder/
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-16
  cve:
    - CVE-2023-29007

attributes:
  nature: INTRUSIVE
  plan: STANDARD
  duration: FAST
compliance_standards:
  GDPR:
    - Article 32
    - Article 25
  HIPAA:
    - 45 CFR ยง 164.308(a)(1)(ii)(A)
    - 45 CFR ยง 164.312(a)(2)(i)
  SOC 2:
    - System Configuration and Management Controls
    - Access and Authorization Settings
  PCI DSS:
    - Requirement 2.2
    - Requirement 6.2
  ISO 27001:
    - A.12.1.1
    - A.12.6.2
  NIST 800-53:
    - CM-6
    - AC-17
  CSA CCM:
    - IVS-09
    - TVM-04
  CIS Controls:
    - IG1 Safeguard 4.6
    - IG1 Safeguard 5.5
  FedRAMP:
    - CM-6
    - AC-17
  NIST 800-171:
    - 3.4.6
    - 3.5.7
  FISMA:
    - CM-6
    - AC-17
  Cybersecurity Maturity Model Certification (CMMC):
    - CM.2.068
    - AC.2.008
api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300
  url:
    extract: urlVar

execute:
  type: single
  requests:
    - req:
        - modify_url: ${urlVar}/.git/config

validate:
  response_code:
    eq: 200
  response_payload:
    length:
      gt: 0
    contains_all:
      - "[core]"
    not_contains:
      - '<html'
      - '<body'
      - '<HTML'
      - '<BODY'
      - '<Html'
      - '<Body'
      - <html>
      - </html>
