id: JETTY_CONFIG_EXPOSED
info:
  name: "Jetty Config Exposed"
  description: >
    "This vulnerability occurs when sensitive configuration files of the Jetty server are accessible over the web, potentially exposing internal settings and configurations."
  details: >
    "When configuration files such as `web.xml` or `jetty.xml` are exposed, attackers can gain insight into the application's setup, security configurations, and possible vulnerabilities. Accessing these files may allow unauthorized users to understand the deployment structure and exploit misconfigurations or weaknesses."
  impact: >
    "Exposing Jetty configuration files can lead to significant security risks, including information disclosure and potential attacks on the server. Attackers can exploit exposed settings to compromise the application, alter its behavior, or gain unauthorized access to sensitive data. Proper server configuration and access controls are essential to mitigate this risk."

  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: JETTY_CONFIG_EXPOSED
  severity: LOW
  references:
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"

  cwe:
    - CWE-200
    - CWE-213
  cve:
    - CVE-2018-10245

attributes:
  nature: NON-INTRUSIVE
  plan: STANDARD
  duration: FAST
api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300

wordLists:
  filePath:
    - web.xml
    - jetty.xml

execute:
  type: single
  requests:
    - req:
        - modify_url: /WEB-INF/${filePath}

validate:
  response_code:
    gte: 200
    lt: 300
  response_payload:
    length:
      gt: 0
    contains_all:
      - jetty.xml
      - DOCTYPE

strategy:
  run_once: /
