id: JS_ENV_CONFIG_DETECT
info:
  name: "JavaScript Environment Configuration Detection Test"
  description: "JavaScript Environment Configuration Detection Test involves checking for misconfigurations in the JavaScript environment that may expose sensitive information or vulnerabilities. This test typically checks whether environment variables, debug information, or configurations intended for development are accessible in production. If exposed, attackers can gain insights into the server's internal configuration, potentially leading to exploitation. Proper environment management, including hiding sensitive data, is essential to mitigate risks."
  details: "JavaScript Environment Configuration Detection Test identifies whether sensitive environment variables or configuration settings are inadvertently exposed in the JavaScript runtime, especially in production environments. This could include information such as API keys, database credentials, or debugging flags, which should only be available to trusted users or internal processes. If improperly exposed through misconfigurations in code, errors, or logging, attackers could leverage this data to launch further attacks or gain unauthorized access. Securing the environment through proper configuration and minimizing exposure is key to reducing these risks."
  impact: "The impact of JavaScript Environment Configuration Detection can be significant, as exposed environment configurations may reveal sensitive data like API keys, database credentials, or other internal configurations. This information can be exploited by attackers to gain unauthorized access, escalate privileges, or compromise the application. Additionally, exposed debug information could provide attackers with insights into potential vulnerabilities, making the system more susceptible to targeted attacks or data breaches. Proper environment management and secure coding practices are essential to mitigate such risks."
  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: JS_ENV_CONFIG_DETECT
  severity: MEDIUM
  references:
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-200
    - CWE-16
  cve:
    - CVE-2021-43798

attributes:
  nature: NON_INTRUSIVE
  plan: PRO
  duration: FAST
compliance_standards: compliance/security-misconfiguration.conf
api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300
  response_payload:
    length:
      gt: 0
wordLists:
  paths:
    - "/env.js"
    - "/env.development.js"
    - "/env.production.js"
    - "/env.test.js"
    - "/env.dev.js"
    - "/env.prod.js"
execute:
  type: single
  requests:
    - req:
        - modify_url: "${paths}"
        - modify_method: GET
        - replace_body: '{}'
validate:
  response_code:
    eq: 200
  response_payload:
    length:
      gt: 0
    contains_either:
      - "module.exports"
      - "const audience"
      - "const domain"
      - "NODE_ENV"
      - "LOG_LEVEL"
    not_contains:
      - "Bootstrap"
      - "jQuery"
      - "CSS TRANSITION SUPPORT"
      - "is_ad_blocked"
  response_headers:
    for_one:
      key:
        eq: "content-type"
      value:
        eq: "application/javascript"
strategy:
  run_once: /
