id: KAFKA_BROKER_CONFIG_EXPOSED
info:
  name: Exposed Kafka broker config
  description: "Exposed Kafka broker config endpoint found."
  details: >
    "The Kafka broker config endpoint is publicly accessible, allowing anyone to access and view detailed system and application broker config, potentially revealing sensitive information."
  impact: "Exposing Kafka broker config can provide insights into the system, potentially aiding attackers in identifying vulnerabilities and exploiting them."
  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: KAFKA_BROKER_CONFIG_EXPOSED
  severity: LOW
  references:
    - https://docs.confluent.io/platform/current/kafka-rest/api.html#configs-v3
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-16
    - CWE-200

attributes:
  nature: INTRUSIVE
  plan: FREE
  duration: FAST
compliance_standards:
  GDPR:
    - Article 32
    - Article 25
  HIPAA:
    - 45 CFR ยง 164.308(a)(1)(ii)(A)
    - 45 CFR ยง 164.312(a)(2)(i)
  SOC 2:
    - System Configuration and Management Controls
    - Access and Authorization Settings
  PCI DSS:
    - Requirement 2.2
    - Requirement 6.2
  ISO 27001:
    - A.12.1.1
    - A.12.6.2
  NIST 800-53:
    - CM-6
    - AC-17
  CSA CCM:
    - IVS-09
    - TVM-04
  CIS Controls:
    - IG1 Safeguard 4.6
    - IG1 Safeguard 5.5
  FedRAMP:
    - CM-6
    - AC-17
  NIST 800-171:
    - 3.4.6
    - 3.5.7
  FISMA:
    - CM-6
    - AC-17
  Cybersecurity Maturity Model Certification (CMMC):
    - CM.2.068
    - AC.2.008
api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300
  url:
    regex: .*clusters/.*/broker-config.*

execute:
  type: single
  requests:
    - req: []

validate:
  response_code:
    eq: 200

  response_payload:
    length:
      gt: 0
    not_contains:
      - <html>
      - </html>
    contains_either:
      - 'KafkaClusterConfig'
      - 'KafkaClusterConfigList'

strategy:
  run_once: /
