id: KAFKA_BROKER_CONFIG_EXPOSED
info:
  name: Exposed Kafka broker config
  description: "Exposed Kafka broker config endpoint found."
  details: >
    "The Kafka broker config endpoint is publicly accessible, allowing anyone to access and view detailed system and application broker config, potentially revealing sensitive information."
  impact: "Exposing Kafka broker config can provide insights into the system, potentially aiding attackers in identifying vulnerabilities and exploiting them."
  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: KAFKA_BROKER_CONFIG_EXPOSED
  severity: LOW
  references:
    - https://docs.confluent.io/platform/current/kafka-rest/api.html#configs-v3
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-16
    - CWE-200

attributes:
  nature: NON_INTRUSIVE
  plan: STANDARD
  duration: FAST


api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300
  url:
    regex: .*clusters/.*/broker-config.*

execute:
  type: single
  requests:
    - req: []

validate:
  response_code:
    eq: 200

  response_payload:
    length:
      gt: 0
    not_contains:
      - <html>
      - </html>
    contains_either:
      - 'KafkaClusterConfig'
      - 'KafkaClusterConfigList'

strategy:
  run_once: /
