id: KUBERNETES_KUSTOMIZATION_DISCLOSURE
info:
  name: Kubernetes Kustomization Disclosure
  description: "Search for the presence of Kubernetes Kustomization files (kustomization.yml) on the provided URLs."
  details: >
    "Kubernetes Kustomization Disclosure involves searching for the presence of Kubernetes Kustomization files (kustomization.yml) on the provided URLs. These files define customizations for Kubernetes deployments and may contain sensitive configuration information such as API versions, resource definitions, namespaces, and labels. Identifying and addressing this vulnerability is critical to prevent unauthorized access, protect sensitive data, and maintain the integrity of Kubernetes deployments."
  impact: "Exposing Kubernetes Kustomization files reveals sensitive configuration details, enabling attackers to gain insights into the deployment structure and potentially launch unauthorized access, data leaks, or further attacks."
  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: KUBERNETES_KUSTOMIZATION_DISCLOSURE
  severity: MEDIUM
  references:
    - https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/kubernetes-kustomization-disclosure.json
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-200
    - CWE-16
  cve:
    - CVE-2021-41254

attributes:
  nature: NON-INTRUSIVE
  plan: STANDARD
  duration: FAST
compliance_standards:
  GDPR:
    - Article 32
    - Article 25
  HIPAA:
    - 45 CFR ยง 164.308(a)(1)(ii)(A)
    - 45 CFR ยง 164.312(a)(2)(i)
  SOC 2:
    - System Configuration and Management Controls
    - Access and Authorization Settings
  PCI DSS:
    - Requirement 2.2
    - Requirement 6.2
  ISO 27001:
    - A.12.1.1
    - A.12.6.2
  NIST 800-53:
    - CM-6
    - AC-17
  CSA CCM:
    - IVS-09
    - TVM-04
  CIS Controls:
    - IG1 Safeguard 4.6
    - IG1 Safeguard 5.5
  FedRAMP:
    - CM-6
    - AC-17
  NIST 800-171:
    - 3.4.6
    - 3.5.7
  FISMA:
    - CM-6
    - AC-17
  Cybersecurity Maturity Model Certification (CMMC):
    - CM.2.068
    - AC.2.008
api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300
  url:
    extract: urlVar

execute:
  type: single
  requests:
    - req:
        - modify_url: ${urlVar}/kustomization.yml

validate:
  response_code:
    eq: 200
  response_payload:
    contains_either:
      - "apiVersion:"
      - "resources:"
      - "namespace:"
      - "commonLabels:"
      - "Kustomization"
  response_headers:
    for_one:
      value:
        contains_either:
          - 'application/yaml'
          - 'Application/Yaml'
          - 'APPLICATION/YAML'
          - 'Application/yaml'
          - 'application/Yaml'
