id: OPENAPI_EXPOSURE
info:
  name: "OpenAPI Documentation Exposure"
  description: "This test refers to the unintended public accessibility of OpenAPI documentation, which describes the APIs available in an application, including their endpoints, request/response formats, and security requirements. If this documentation is exposed without adequate security measures, it can provide attackers with valuable insights into the application’s architecture and functionality. This information can be exploited to launch targeted attacks or identify vulnerabilities. To mitigate risks, it is essential to restrict access to OpenAPI documentation and implement proper authentication and authorization controls."
  details: "OpenAPI Documentation Exposure occurs when the API documentation is publicly accessible without proper security controls, allowing anyone to view detailed information about the API endpoints, methods, parameters, and response structures. This exposure can give attackers a roadmap of the application, enabling them to identify potential vulnerabilities or weaknesses in the API. Additionally, it may expose sensitive data models or business logic, further increasing the risk of exploitation. To protect against this exposure, organizations should implement access controls, secure the documentation behind authentication, and limit visibility to authorized users only."
  impact: "The impact of OpenAPI Documentation Exposure can be severe, as it provides attackers with detailed insights into the API’s structure, making it easier to exploit vulnerabilities and craft targeted attacks. This can lead to unauthorized access, data breaches, and the potential for service disruptions. Moreover, the exposed documentation may reveal sensitive information about the application's architecture and business logic, increasing the risk of exploitation and significant financial and reputational damage to the organization. Additionally, regulatory consequences may arise if sensitive data is compromised due to inadequate security measures."
  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: OPENAPI_EXPOSURE
  severity: MEDIUM
  references:
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-200
    - CWE-16
  cve:
    - CVE-2021-43798

attributes:
  nature: NON-INTRUSIVE
  plan: STANDARD
  duration: FAST
compliance_standards:
  GDPR:
    - Article 32
    - Article 25
  HIPAA:
    - 45 CFR § 164.308(a)(1)(ii)(A)
    - 45 CFR § 164.312(a)(2)(i)
  SOC 2:
    - System Configuration and Management Controls
    - Access and Authorization Settings
  PCI DSS:
    - Requirement 2.2
    - Requirement 6.2
  ISO 27001:
    - A.12.1.1
    - A.12.6.2
  NIST 800-53:
    - CM-6
    - AC-17
  CSA CCM:
    - IVS-09
    - TVM-04
  CIS Controls:
    - IG1 Safeguard 4.6
    - IG1 Safeguard 5.5
  FedRAMP:
    - CM-6
    - AC-17
  NIST 800-171:
    - 3.4.6
    - 3.5.7
  FISMA:
    - CM-6
    - AC-17
  Cybersecurity Maturity Model Certification (CMMC):
    - CM.2.068
    - AC.2.008
api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300
  response_payload:
    length:
      gt: 0
execute:
  type: single
  requests:
    - req:
        - modify_url: "/openapi.json"
        - modify_method: GET
        - replace_body: '{}'
validate:
  response_code:
    eq: 200
  response_payload:
    length:
      gt: 0
    contains_all:
      - openapi
      - paths
  response_headers:
    for_one:
      key:
        eq: "content-type"
      value:
        contains_either:
          - application/openapi+json
          - application/json
strategy:
  run_once: /
