id: PROMETHEUS_CONFIG_API_EXPOSURE
info:
  name: "Prometheus Config API Endpoint Exposure"
  description: "Prometheus Config API Endpoint Exposure refers to a security risk where the configuration API endpoints of Prometheus are exposed without adequate protection. These endpoints allow access to sensitive configuration settings, including scrape targets, alert rules, and credentials for external services. If left unsecured, attackers can modify configurations, access confidential information, or disrupt monitoring services, potentially leading to system instability or unauthorized access to sensitive data. Proper authentication and access controls are necessary to mitigate this risk."
  details: "Prometheus Config API Endpoint Exposure occurs when the API endpoints responsible for managing and retrieving configuration details in Prometheus are left unprotected. These endpoints can provide access to critical settings such as scrape targets, alert configurations, and credentials used to monitor external systems. If exposed, attackers can modify or view these configurations, potentially disabling monitoring, tampering with alerts, or accessing sensitive information. To prevent such exposure, organizations should secure the API endpoints with strong authentication, restrict access to trusted users, and regularly review configurations for vulnerabilities."
  impact: "The impact of Prometheus Config API Endpoint Exposure can be significant, allowing attackers to alter or disable critical monitoring configurations, leading to a loss of visibility into system health and performance. Malicious actors could modify alert rules, disable monitoring of key services, or access sensitive credentials, potentially causing operational disruptions or escalating attacks on other systems. This exposure can result in undetected outages, data breaches, or compliance violations, ultimately leading to financial losses, reputational damage, and legal consequences for the affected organization."
  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: PROMETHEUS_CONFIG_API_EXPOSURE
  severity: MEDIUM
  references:
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-200
    - CWE-16
  cve:
    - CVE-2021-43798

attributes:
  nature: NON_INTRUSIVE
  plan: FREE
  duration: FAST
compliance_standards: https://github.com/akto-api-security/tests-library/blob/hotfix/fixed_some_minor_bugs/compliance/security-misconfiguration.conf
api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300
  response_payload:
    length:
      gt: 0
wordLists:
  paths:
    - "/api/v1/status/config"
execute:
  type: single
  requests:
    - req:
        - modify_url: "${paths}"
        - modify_method: GET
        - replace_body: '{}'
validate:
  response_code:
    eq: 200
  response_payload:
    length:
      gt: 0
    not_contains:
      - <html>
      - </html>
    contains_all:
      - '"status": "success":'
      - '"data":'
      - '"yaml":'
  response_headers:
    for_one:
      key:
        eq: "content-type"
      value:
        eq: "application/json"
strategy:
  run_once: /
