id: REDIS_CONFIG
info:
  name: Redis Configuration File Exposure
  description: "Redis configuration file (redis.conf) was exposed."
  details: >
              "The Redis configuration file (redis.conf) was found at the specified URL. This file contains sensitive information such as server binding, protected mode settings, and port configuration."
  impact: "The exposure of the Redis configuration file can potentially lead to unauthorized access, modification, or exploitation of the Redis server and its data."
  remediation: "To address Redis configuration file exposure, restrict access with strict file permissions and avoid hardcoding sensitive data. Encrypt sensitive information within the files and regularly audit permissions to prevent unauthorized access. These measures bolster security and safeguard against potential disclosure of confidential data."
  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: REDIS_CONFIG
  severity: MEDIUM
  references:
    - https://redis.io/docs/manual/config/
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-16
    - CWE-200
  cve:
    - CVE-2023-36824
    - CVE-2022-0543

api_selection_filters:
  response_code:
    gte: 200
    lt: 300
  url:
    extract: urlVar
  
execute:
  type: single
  requests:
    - req:
      - modify_url: ${urlVar}/redis.conf

validate:
  response_code:
    eq: 200
  response_payload:
    contains_all:
      - "bind"
      - "protected-mode"
      - "port "
  response_headers:
    for_one:
      value:
        contains_all:
          - "application/octet-stream"