id: SFTP_CONFIG_EXPOSURE
info:
  name: SFTP Config File Disclosure
  description: " Detects the exposure of SFTP configuration files."
  details: >
              "Searches for the presence of SFTP configuration files, typically stored in "sftp-config.json". These files may contain sensitive information such as host, username, password, and remote paths."
  impact: "Exposing SFTP configuration files can compromise the security of file transfer operations, leading to unauthorized access and potential data breaches."
  remediation: "To address SFTP config file disclosure vulnerabilities, limit access permissions on configuration files to prevent unauthorized reading. Ensure that sensitive information such as usernames, passwords, and private keys are not stored in plaintext within configuration files. Encrypt sensitive data or use secure key management solutions. Regularly audit file permissions and configurations to detect any inadvertent exposures. Additionally, consider implementing network segmentation and intrusion detection systems to monitor and prevent unauthorized access attempts."
  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: SFTP_CONFIG_EXPOSURE
  severity: HIGH
  references:
    - https://blog.sucuri.net/2012/11/psa-sftpftp-password-exposure-via-sftp-config-json.html
    - https://www.acunetix.com/vulnerabilities/web/sftp-ftp-credentials-exposure/
    - https://codexns.io/products/sftp_for_sublime/settings
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-16
    - CWE-200
  cve:
    - CVE-2023-38951

api_selection_filters:
  response_code:
    gte: 200
    lt: 300
  url:
    extract: urlVar
  
execute:
  type: single
  requests:
    - req:
      - modify_url: ${urlVar}/sftp-config.json

validate:
  response_code:
    eq: 200
  response_payload:
    contains_all:
      - 'host'
      - 'user'
      - 'password'
      - 'remote_path'