id: TRAEFIK_LOG_EXPOSED
info:
  name: Traefik Log Exposed
  description: >
    The Traefik log files can contain sensitive information regarding traffic patterns, requests, and backend service interactions. If these logs are exposed, they can be exploited by malicious actors.
  details: >
    This vulnerability arises when the Traefik log files are accessible over the internet or to unauthorized users. The logs may include sensitive data such as user IP addresses, request URLs, and even authentication details if not properly sanitized. Exposure of these logs can lead to privacy violations and security breaches.
  impact: >
    Exposing Traefik logs can result in unauthorized access to sensitive information, allowing attackers to analyze traffic patterns, identify weaknesses, and potentially exploit services. This could lead to data breaches, service disruptions, or further attacks on the infrastructure.

  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: TRAEFIK_LOG_EXPOSED
  severity: LOW
  references:
    - https://doc.traefik.io/traefik/observability/logs/
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa8-security-misconfiguration.md"
  cwe:
    - CWE-16
    - CWE-200
  cve:
    - CVE-2020-11959

attributes:
  nature: NON_INTRUSIVE
  plan: STANDARD
  duration: FAST


api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300
  response_payload:
    length:
      gt: 0

wordLists:
  attemptList:
    - "/etc/traefik/traefik.log"
    - "/var/log/traefik/traefik.log"
    - traefik.log

execute:
  type: single
  requests:
    - req:
        - modify_url: ${attemptList}

validate:
  response_code:
    eq: 200
  response_payload:
    length:
      gt: 0
    contains_either:
      - "traefik.http."
      - "traefik.tls."
      - "traefik.docker."
      - "traefik.enable"
      - "sticky.cookie"
      - "weighted.services"
      - "auth.basic.users"
      - "auth.forward.address"
      - "tls.certificates"
      - "insecureSkipVerify"
      - "accessLog.filePath"
      - "accessLog.filters.statuscodes"
      - "log.level=DEBUG"
      - "tracing.serviceName"
    not_contains:
      - Error
      - Internal Server
      - Failed
      - Unauthorized
      - access denied
      - Forbidden
      - Method Not allowed
      - Gateway timeout
      - request timeout
      - server error
      - server busy
      - authentication error
      - authorization error
      - validation error
      - Permission Denied
      - invalid token
      - token expired
      - session expired
      - session timeout
      - unexpected error
      - unable to process request
      - bad request
      - service unavailable
      - account is locked
      - account is blocked
      - multiple failed attempts
      - Attention Required!
      - CloudFlare
      - "Sorry, you have been blocked"

strategy:
  run_once: /
