id: VARNISH_CONFIG_EXPOSED
info:
  name: Varnish Config Exposed
  description: >
    The configuration files of Varnish Cache can contain sensitive information, including cache settings, backend server details, and authentication credentials. If exposed, these configurations can pose a significant security risk.
  details: >
    This vulnerability arises when the Varnish configuration files are accessible through the web server. Exposure of these files can provide attackers with insights into the caching strategies, backend services, and other operational details that could be exploited for malicious purposes.
  impact: >
    Exposed Varnish configuration files can lead to unauthorized access, cache manipulation, and potential bypass of security measures. Attackers may use the information obtained to compromise the integrity and confidentiality of the cached content or the underlying services.

  category:
    name: SM
    shortName: Misconfiguration
    displayName: Security Misconfiguration (SM)
  subCategory: VARNISH_CONFIG_EXPOSED
  severity: LOW
  references:
    - https://varnish-cache.org/docs/7.6/reference/
    - https://blog.lighttpd.net/articles/2006/04/02/log-condition-handling-the-hidden-feature-for-debuging/
  cwe:
    - CWE-16
    - CWE-200
  cve:
    - CVE-2020-11959

settings:
  nature: NON-INTRUSIVE
  plan: STANDARD
api_selection_filters:
  method:
    neq: "OPTIONS"
  response_code:
    gte: 200
    lt: 300
  response_payload:
    length:
      gt: 0

wordLists:
  attemptList:
    - /etc/default/varnish
    - /etc/varnish/default.vcl
    - /etc/sysconfig/varnish

execute:
  type: single
  requests:
    - req:
        - modify_url: ${attemptList}

validate:
  response_code:
    eq: 200
  response_payload:
    length:
      gt: 0
    percentage_match:
      lt: 10
    percentage_match_schema:
      lt: 10
    not_contains:
      - Error
      - Internal Server
      - Failed
      - Unauthorized
      - access denied
      - Forbidden
      - Method Not allowed
      - Gateway timeout
      - request timeout
      - server error
      - server busy
      - authentication error
      - authorization error
      - validation error
      - Permission Denied
      - invalid token
      - token expired
      - session expired
      - session timeout
      - unexpected error
      - unable to process request
      - bad request
      - service unavailable
      - account is locked
      - account is blocked
      - multiple failed attempts
      - Attention Required!
      - CloudFlare
      - "Sorry, you have been blocked"

strategy:
  run_once: /
