id: PAYLOAD_KEYS_INVALID_VALUES
info:
  name: "Payload Keys Invalid Values"
  description: >
    This test focuses on evaluating how the application handles invalid values within payload keys, which may lead to unexpected behavior or errors.
  details: >
    The test involves iteratively inserting various invalid values, such as control characters, multi-code point emojis, single-code point emojis, and excessive whitespace within the payload keys to assess the application's response and robustness.
  impact: >
    Inadequate handling of invalid values in payload keys can result in application errors, unexpected behavior, or potential security vulnerabilities.

  category:
    name: INPUT
    shortName: Input Validation
    displayName: Input Validation (INPUT)
  subCategory: PAYLOAD_KEYS_INVALID_VALUES
  severity: LOW
  tags:
    - Business logic
    - OWASP top 10
    - HackerOne top 10
  references:
    - https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html
    - https://owasp.org/www-project-developer-guide/draft/design/web_app_checklist/validate_inputs/
  cwe:
    - CWE-20
  cve:
    - CVE-2018-20679
    - CVE-2019-14271

attributes:
  nature: INTRUSIVE
  plan: PRO
  duration: FAST
compliance_standards: compliance/input-validation.conf
api_selection_filters:
  response_code:
    gte: 200
    lt: 300
  method:
    neq: OPTIONS
  response_payload:
    length:
      gt: 0
    not_contains:
      - Error
      - Internal Server
      - Failed
      - Unauthorized
      - access denied
      - Forbidden
      - Method Not allowed
      - Gateway timeout
      - request timeout
      - server error
      - server busy
      - authentication error
      - authorization error
      - validation error
      - Permission Denied
      - invalid token
      - token expired
      - session expired
      - session timeout
      - unexpected error
      - unable to process request
      - bad request
      - service unavailable
      - account is locked
      - account is blocked
      - multiple failed attempts
  request_payload:
    for_one:
      key:
        regex: .*
        extract: userKey
      value:
        extract: userVal

execute:
  type: multiple
  requests:
    - req:
    # checking if the key is actually important, if it is only then continue with attack.
        - delete_body_param: ${userKey}
        - validate:
            response_code:
              gte: 400
        - success: x2
        - failure: exit
    - req:
        - modify_body_param:
            userKey: "${userVal}${attemptValues}"
        - validate:
            response_code:
              gte: 200
              lt: 300
            response_payload:
              length:
                gt: 0
              percentage_match:
                gte: 90
              not_contains: ${badList}
        - success: vulnerable
        - failure: x3
    - req:
        - modify_body_param:
            userKey: "${attemptValues}"
        - validate:
            response_code:
              gte: 200
              lt: 300
            response_payload:
              length:
                gt: 0
              percentage_match:
                gte: 90
              not_contains: ${badList}
        - success: vulnerable
        - failure: x4
    - req:
        - modify_body_param:
            userKey: "${attemptValues}${userVal}"
        - validate:
            response_code:
              gte: 200
              lt: 300
            response_payload:
              length:
                gt: 0
              percentage_match:
                gte: 90
              not_contains: ${badList}
        - success: vulnerable
        - failure: x5
    - req:
        - modify_body_param:
            userKey: "${attemptValues2}"
        - validate:
            response_code:
              gte: 200
              lt: 300
            response_payload:
              length:
                gt: 0
              percentage_match:
                gte: 90
              not_contains: ${badList}
        - success: vulnerable

wordLists:
  attemptValues:
    # null values
    - \u0000
    - \0
    - "NULL"
    - "null"
    - "0000"
    - \x00
    - "\0"
    - "\0"
    - NUL
    - "NUL"
    - "\0"
    - "\000"
    - 0x00
    - "\0null"
    # whitespace
    - "      "
    # emojis
    - ":)"
  attemptValues2:
    - ""
  badList:
    - Error
    - Internal Server
    - Failed
    - Unauthorized
    - access denied
    - Forbidden
    - Method Not allowed
    - Gateway timeout
    - request timeout
    - server error
    - server busy
    - authentication error
    - authorization error
    - validation error
    - Permission Denied
    - invalid token
    - token expired
    - session expired
    - session timeout
    - unexpected error
    - unable to process request
    - bad request
    - service unavailable
    - account is locked
    - account is blocked
    - multiple failed attempts
    - Attention Required!
    - CloudFlare
    - "Sorry, you have been blocked"
