id: PAYLOAD_INVALID_VALUES
info:
  name: Payload Invalid Values
  description: >
    This test evaluates how the server handles various invalid payloads in HTTP requests to identify potential vulnerabilities arising from improper validation and processing.
  details: >
    The test involves sending a series of HTTP requests with different types of invalid payloads, which may include empty bodies, malformed JSON structures, and unsupported formats.
  impact: >
    Servers that do not handle invalid payloads appropriately may be susceptible to a range of security issues, including denial of service and unexpected application behavior.

  category:
    name: INPUT
    shortName: Input Validation
    displayName: Input Validation (INPUT)
  subCategory: PAYLOAD_INVALID_VALUES
  severity: LOW
  tags:
    - Business logic
    - OWASP top 10
    - HackerOne top 10
  references:
    - https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html
    - https://owasp.org/www-project-developer-guide/draft/design/web_app_checklist/validate_inputs/
  cwe:
    - CWE-20
  cve:
    - CVE-2018-20679
    - CVE-2019-14271

settings:
  nature: INTRUSIVE
api_selection_filters:
  response_code:
    gte: 200
    lt: 300
  method:
    neq: OPTIONS
    or:
      - eq: PUT
      - eq: POST
  response_payload:
    length:
      gt: 0
    not_contains:
      - Error
      - Internal Server
      - Failed
      - Unauthorized
      - access denied
      - Forbidden
      - Method Not allowed
      - Gateway timeout
      - request timeout
      - server error
      - server busy
      - authentication error
      - authorization error
      - validation error
      - Permission Denied
      - invalid token
      - token expired
      - session expired
      - session timeout
      - unexpected error
      - unable to process request
      - bad request
      - service unavailable
      - account is locked
      - account is blocked
      - multiple failed attempts
  query_param:
    for_one:
      key:
        regex: .*
        extractMultiple: queryKeys

wordLists:
  attemptValues:
    - ""
    - "{}"
    - "null"
    - "\0"

execute:
  type: single
  requests:
    - req:
        - replace_body: ${attemptValues}
        - ${queryKeys}:
            for_all:
              - delete_query_param: ${iteratorKey}

validate:
  response_code:
    gte: 200
    lt: 300
  response_payload:
    length:
      gt: 0
    not_contains:
      - Error
      - Internal Server
      - Failed
      - Unauthorized
      - access denied
      - Forbidden
      - Method Not allowed
      - Gateway timeout
      - request timeout
      - server error
      - server busy
      - authentication error
      - authorization error
      - validation error
      - Permission Denied
      - invalid token
      - token expired
      - session expired
      - session timeout
      - unexpected error
      - unable to process request
      - bad request
      - service unavailable
      - account is locked
      - account is blocked
      - multiple failed attempts
      - Attention Required!
      - CloudFlare
      - "Sorry, you have been blocked"
