
id: SecurityMisconfig 
filter:
  or:
    - response_payload:
        regex:
          - (?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|6(?:011|5[0-9]{2})[0-9]{12}|(?:2131|1800|35\d{3})\d{11}) 

    - response_payload:
        regex:
          - (?i)\b(?:java[\.a-z]+E(?:xception|rror)|(?:org|com)\.[\.a-z]+Exception|Exception in thread \"[^\"]*\"|at[\s\x0b]+(?:ja(?:vax?|karta)|org|com))\b
    - request_headers:
        for_one:
          key:
            eq: host
          value:
            regex: ^(?:\d{1,3}(?:\.\d{1,3}){3}|[a-zA-Z0-9.-]+:\d+)$ 
info:
  name: "SecurityMisconfig"
  description: "Security misconfigurations occur when systems, applications, or APIs are not securely configured, exposing vulnerabilities that attackers can exploit. This includes improper settings, default configurations, unnecessary features enabled, or misconfigured permissions, leading to unauthorized access or data exposure."
  details: "Security misconfigurations arise from insecure default settings, incomplete configurations, open cloud storage, misconfigured HTTP headers, or verbose error messages exposing sensitive information. Examples include unpatched systems, exposed admin interfaces, or unnecessary services running. Mitigation involves secure configuration baselines, regular audits, and minimizing attack surfaces."
  impact: "Exploiting security misconfigurations can lead to unauthorized access, data breaches, or full system compromise. Attackers may gain access to sensitive data, escalate privileges, or disrupt operations, causing financial loss, reputational damage, or regulatory penalties."
  category:
    name: "SecurityMisconfig"
    displayName: "SecurityMisconfig"
    subCategory: "SecurityMisconfig"
  severity: MEDIUM
