id: MISCONFIGURED_HSTS_HEADER
info:
  name: "Misconfigured HTTP Strict-Transport-Security Header"
  description: >
    "This test identifies misconfigurations in the HTTP Strict-Transport-Security (HSTS) header, where mandatory attributes or values are missing, incorrect, or improperly formatted. The HSTS header must be correctly set to enforce HTTPS connections, ensuring that the application communicates securely."
  details: >
    "The HSTS header requires specific parameters to function properly. For example, 'max-age' is a required attribute that defines the period (in seconds) for which the browser should enforce HTTPS-only communication. A missing or incorrectly set 'max-age' value results in a non-compliant HSTS header, which can undermine the security policy. Additionally, optional parameters like 'includeSubDomains' and 'preload' must be correctly formatted to ensure comprehensive enforcement across subdomains and to support browser preload lists."
  impact: >
    "A misconfigured HSTS header can significantly weaken the security of an application by failing to enforce strict HTTPS communication. Without proper enforcement, the application becomes vulnerable to downgrade attacks, such as SSL stripping, where attackers attempt to redirect traffic from HTTPS to HTTP. This leaves sensitive information exposed and can lead to data breaches, man-in-the-middle attacks, or session hijacking. Ensuring that the HSTS header is correctly configured and compliant with security specifications is crucial for maintaining secure communications."

  category:
    name: MHH
    shortName: Misconfigured HTTP Headers
    displayName: Misconfigured HTTP Headers (MHH)
  subCategory: MISCONFIGURED_X_FRAME_OPTIONS_HEADER
  severity: LOW
  tags:
    - Business logic
    - OWASP top 10
    - HackerOne top 10
  references:
    - "https://web.dev/security-headers/"
    - "https://www.keycdn.com/blog/http-security-headers"
    - "https://www.invicti.com/white-papers/whitepaper-http-security-headers"
    - "https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Strict_Transport_Security_Cheat_Sheet.html"
  cwe:
    - CWE-693
  cve:
    - CVE-2022-41915
    - CVE-2022-37436

attributes:
  nature: INTRUSIVE
  plan: FREE
  duration: FAST
api_selection_filters:
  response_code:
    gte: 200
    lt: 300
  method:
    neq: "OPTIONS"
  or:
    - response_headers:
        for_one:
          key:
            eq: Strict-Transport-Security
          value:
            regex: "^(?!.*max-age).*"
    - response_headers:
        regex: ".*Strict-Transport-Security.*Strict-Transport-Security.*"
    - request_payload:
        regex: "<meta[^>]*http-equiv=['\"]Strict-Transport-Security['\"][^>]*>"

execute:
  type: single
  requests:
    - req: []

validate:
  response_code:
    gte: 200
    lt: 300
  response_payload:
    length:
      gt: 0
    percentage_match:
      gte: 40

strategy:
  run_once: /
